### ISSUE TITLE
Add API for ranges

### ISSUE THREAD

**Issue by WillBAnders** [jackfirth/rebellion#315] opened 2019-10-24 23:19 UTC
This issue is a summation of ideas and discussion regarding adding an API for working with ranges. It is intended to help finalize the design in preparation for a PR.

## Goals

 - General:
    - [X] Empty ranges are supported
    - [X] Non-discrete ranges are supported
    - [X] Unbounded ranges are supported
    - [ ] Decreasing ranges are supported
    - [X] Allow custom comparator
 - Canonical Form:
    - A canonical form of a range is one where ranges representing the same values are stored in the same way, which allows for comparison, conjoined ranges, etc. For example, `(0, 10)` and `[1, 9]` are the same range (over integers), however cannot effectively be compared.
    - [X] Ranges are [closed, open) for discrete values
    - [X] Ranges are increasing
    - [X] The empty range is `[0, 0)`
 - Creation:
    - [X] Easy creation of standard ranges (incl-incl, excl-excl, incl-excl, excl-incl)
    - [ ] Easy creation of unbounded ranges (above-incl, above-excl, below-incl, below-excl)
    - [X] Callers can pass in the inclusiveness of a bound as a parameter
 - Iteration:
    - [X] Ranges can be iterated over
    - [X] Forwards and backwards iteration is supported
    - [ ] Specifying the step size is supported
    - [ ] Map, reduce, and other functional forms
 - Rebellion Integration:
    - TBD: Integration with comparators and transducers were discussed, but needs to be finalized. As I'm not too familiar with Rebellion, additional input here would be helpful both with design and implementation.

### General

```racket
(define range (range 0 10))

(range/lower range) ; 0
(range/upper range) ; 0
(range/lower-incl range) ; #t
(range/lower-excl range) ; #f
(range/upper-incl range) ; #f
(range/upper-excl range) ; #t

(range/contains range 5) ; #t
(range/contains range -5) ; #f
(range/contains range 0) ; #t
(range/contains range 10) ; #f
```

> If decreasing ranges are allowed, then `range/start` and `range/end` should be used.

### Equality & Comparison

Ranges are equal if they have the same bounds (and same inclusivity). Important question:
 - Should equality force a canonical form (as in `(0, 10)` equals `[1, 9]`) or require the developer to manually convert to canonical form for value comparisons?

Additionally, ranges should be comparable and thus sortable based on the bounds: (`[0, 10) is before `[0, 11)`, and both are before `[1, 2)`. This could be useful for something like a Gantt chart.

### Creation

Some proposed syntax for creating ranges. Implementation could be handled with keywords, variants, or potentially a macro to support special characters.

 - 0 to exclusive: `(range 10)`: `[0, 10)`
 - Inclusive-exclusive: `(range 0 10)` -> `[0, 10)`
 - Specify bounds: `(range 0 #t 10 #f)` -> `[0, 10)`
 - Various forms for bounds with different inclusivity:
    - `(range/incl 0 10)`, `(range/excl 0 10)`, `(range/excl-incl 0 10)`
    - `(range #:incl 0 10)`, `(range #:excl 0 10)`, `(range #:excl 0 #:incl 10)`
    - `(range 0 '<= '<= 10)`, `(range 0 '< '< 10)`, `(range 0 '< '<= 10)`
    - `#range[0, 10]`, `#range(0, 10)`, `#range(0, 10]`

### Iteration

Ranges should support both forward and backwards iteration (increasing/decreasing) and should likely also support a step size (most helpful for less-discrete values like decimals). Some potential examples:

```
(range/iter range (λ...))
(range/iter #:reverse range (λ...)) ; or range/iter-rev?
(range/iter range #:step 2 (λ...))
```
> Back to back keywords make something like `(range/iter range #:reverse #:step 2 (λ...))` not possible, unfortunately.

Additionally, it is likely useful to support some form of map/reduce. In the case of map, this would probably produce a list.

## Feedback

Feedback and input on this, especially considering design decisions, would be greatly appreciated. Please let me know if there's anything that seems to be left out!

**Comment by jackfirth** [comment] 2019-10-26 03:36
Thank you very much for putting in this effort to design a range API!

As we talked about on the discord server, there ought to be some way to use a user-supplied comparator to define the range. That aside, I wanted to double-check that I understand what kinds of ranges are supported. All of the following are allowed, right?

- `[3, 7)`
- `[3, 7]`
- `(3, 7]`
- `(3, 7)`
- `[3, ∞)`
- `(∞, 7]`
- `(∞, ∞)`
- `[3, 3)`

And all of the following are disallowed:

- `[7, 3]`
- `[3, 3]`
- `(3, 3)`
- `(3, 3]`
- `[3, ∞]`
- `[∞, 7]`

**Comment by WillBAnders** [comment] 2019-10-26 05:02
Really good clarifying point. So, there are three things at play here which conflict with the examples given: Decreasing ranges, infinity vs unbounded, and canonical forms.

 - Decreasing ranges like `[7, 3]` are theoretically fine - the only reason I can think to prevent them are to avoid situations like `[5, n]` turning into `[5, 12]` and `[5, 1]` where the programmer doesn't expect it. Guava's ranges enforce that the lower bound is less; but I can't see too many benefits to it from a usage perspective (it absolutely makes the implementation easier though).
 - There is a noticeable difference between infinity and an unbounded range. For something like integers it's not important, but with decimal numbers involved values like `+inf.0` and `-inf.0` exist. As such, the ranges `[0, +inf.0)` and `[0, +inf.0]` are different when testing `+inf.0`. Likewise, lower bounds would have to specify a sign in the case of infinity (if it's unbounded, then there isn't even a value - infinity is really only a good representation for numbers). I personally like `[0, *)`.
 - Lastly, in cases like `(3, 3)` or `(3, 3]` I think there's really no harm in these. They're all empty ranges as far as I'm concerned - `3 < x < 3` has no solutions, after all. This is where canonical ranges become important when talking about comparing ranges based on the values they represent - in order to do this, there needs to be a consistent way of writing ranges. The idea of a canonical form is that ranges covering the same values are represented in the same way.

So in total:
 - `[7, 3]` is probably fine. IMO not worth restricting as there's really no harm in it.
 - `[3, ∞]` as unbounded could be `[3, *]` or `[3, *)` (canonical). Same with lower bounds being `(*, 7]` or something. Infinity would be reserved for values which could actually be infinity from doubles.
 - Really, the only restrictions on the endpoints come from canonical form. As such, anything else is pretty much free-for-all - I think each way of representing things conveys a different meaning and there may be use cases for that. But, in order to do mathematical operations involving ranges I think there needs to be a canonical form.

For something so basic there sure is a lot of complexity!

**Comment by jackfirth** [comment] 2019-10-26 07:13
Will attempt to go into more detail analyzing this over the weekend, but here are some open questions I have:

- How should equality of ranges be defined? Are there surprising cases?

- How will comparators fit into the picture?

- Is discrete-ness or continuous-ness a property of the range itself, or merely a property of how a given range is used? That is, is there only _one_ range `[3, 7)` and `range-contains?` can be used with both `5` and `4.1`? Or are there _two different_ ranges with those endpoints, one that's discrete and meant to be used only on integers and one that's continuous and can be used on inexact numbers?

- Similarly, do ranges have directionality? That is, if `[7, 3]` is allowed, is that a _different_ range from `[3, 7]`? My gut says no, that would be very confusing.

- How does this fit in with reducers? Can there be an `into-range` reducer for simultaneously finding the max and min elements of a sequence? Rust defines a special `MinMax` struct type for this purpose, how does that compare to a range-based approach?

- What should the path of the ranges module be? Something in `rebellion/base`? In `rebellion/collection`? Somewhere else?

- Will there be identifier conflicts with the `in-range` and `range` functions of `racket/base`? Is it a problem if there are?

**Comment by WillBAnders** [comment] 2019-10-27 01:59
So, first thing I want to do is to provide a layout of how I would do this using a typed language and what each form means.

 - `Range`: A supertype for all ranges
    - `StandardRange`: A range that is bounded or unbounded, like `[3, 2]`, `[0, *)`, and `(*, *)`.
    - `CanonicalRange`: A `StandardRange` that is in canonical form, defined as bounds being inclusive-exclusive, lower <= upper, and the empty range being `[0, 0)`. This only applies for discrete values. This is also where mathematical operations defined on ranges become possible, as without this there are multiple ways of expressing equivalent ranges.
    - `ConjoinedRange`: A range that consists of multiple `CanonicalRange`s, which is basically the result of `union`s and whatnot. In other words, ranges which allow holes.

I think that with this in mind the layout and properties I'm considering are a bit clearer as it's hard to express without talking about types. Anyways, responses in same order:

 1. Range equality has two forms: one which only considers the values the range contains and the other also considering the structure of how that range is built. The latter is standard equality, the former is what canonical range is for. There are not special cases here.
 1. Natural ordering of ranges is lower-bound, lower-bound-inclusive, upper-bound, upper-bound-exclusive. Essentially, sort by start point followed by end point.
 1. In the context of Racket, the type system will allow any number to be used freely but I consider this to be more of a consequence of dynamic typing rather than something that's a range itself. A good way to justify this is to consider a canonical form - the range `(0, 10]` for integers is equivalent to `[1, 11)`, but `(0.0, 10.0]` for real numbers has no other equivalent representation.
 1. This would be canonical again. `[3, 7]` and `[7, 3]` are the same ranges when considering values, but different ranges considering structure - their iteration order would be different. However, whether to allow decreasing ranges is also a bit of an open question. 
 1. `into-range` would effectively be `enclose`, which takes an iterable/sequence/whatever and returns the minimum range which encloses all of the provided values. This would be an inclusive range on the minimum and maximum values, doable in linear time.
 1. From a type perspective Range is definitely not a Collection. I looked through some of the different options and `rebellion/base` makes the most sense to me, especially with things like comparator and pair in there too.
 1. `(range 0 10)` would conflict with Racket's, which simply generates a list over a range + step. I think that anyone who intends on using a savable range like this would not have an interest in using that. We can also add a `to-list` method to the API to bridge this easier as well. It could also be renamed to `range/create`, but I don't think it will be a significant issue and we can rename-out Racket's if need be.
 1. Sticking to set theory for over values, `intersection`, `union`, and `difference` are possible - these last two may return conjoined ranges. In addition, a `span` method to take multiple ranges and return one (such as the previous example to `[1, 11)` is easily done. I can't think of anything else needed.

**Comment by jackfirth** [comment] 2019-10-27 19:50
I think you're right that ranges shouldn't be collections. That implies to me that there should be a distinction between a range and a _set_ of disjoint ranges. So I think rather than there being a `ConjoinedRange` subtype of ranges, there ought to be a type for contiguous sets.

Furthermore, let's say there's two different kinds of ranges: continuous and discrete. Discrete ranges are always in canonical form and require a discrete domain over their values. So I'm thinking of an API for ranges that looks something like this:

```racket
discrete-integers : discrete-domain?
discrete-naturals : discrete-domain?
(discrete-range [lower-bound cut?] [upper-bound cut?] [domain discrete-domain?])
  -> discrete-range?
(continuous-range [lower-bound cut?] [upper-bound cut?]) -> continuous-range?
discrete-range? : predicate/c
continuous-range? : predicate/c
range? : predicate/c
(range-encloses? [range range?] [other-range range?]) -> boolean?
(range-contains? [range range?] [v any/c]) -> boolean?
(range-lower-bound [range range?]) -> cut?
(range-lower-endpoint [range range?]) -> option?
(range-upper-bound [range range?]) -> cut?
(range-upper-endpoint [range range?]) -> option?
```

Also, I really like the approach of bundling the endpoint and the type of bound together into a single value, so the above signatures are defined in terms of _cuts_, with this API:

```racket
(cut-above [point any/c] [comparator comparator? real<=>]) -> cut?
(cut-below [point any/c] [comparator comparator? real<=>]) -> cut?
cut-above-all : cut?
cut-below-all : cut?
(cut-point [cut cut?]) -> option?
(cut-includes? [cut cut?] [v any/c]) -> boolean?
```

Some examples:

```racket
(continuous-range (cut-below 3) (cut-below 7)) ; 3 <= x < 7
(continuous-range (cut-below 3) (cut-above 7)) ; 3 <= 3 <= 7
(continuous-range (cut-above 3) cut-above-all) ; 3 < x
(continuous-range cut-below-all (cut-above 7)) ; x <= 7
(discrete-range (cut-below -5) (cut-above 7) discrete-integers) ; -5 <= x < 7
(discrete-range (cut-below -5) (cut-above 7) discrete-naturals) ; 0 <= x < 7
```

**Comment by WillBAnders** [comment] 2019-10-28 17:45
Differentiating between continuous and discrete ranges is a good idea. However, one thing to note about enforcing canonical form is that iteration could be different for higher step values. For example, iterating over `[0, 10)` in reverse by 2's could be `8, 6, 4, 2, 0` or `9, 7, 5, 3, 1` depending on how it's handled. I think in many cases, enforcing this is a bit too restrictive and requiring things like domains to set it up is unnecessary. In the majority of cases, it's going to be a range created purely for the purpose of iteration (often by 1's).

I would also consider the way bounds are represented to be an implementation detail. I'm not a fan of Guava's cut system because I believe it to be largely over-engineered without having any benefits. It becomes too difficult to express simple operations.

I would propose the following:
 - Define normal ranges however allowing any combination of endpoints. For now, I believe it's worth enforcing that the range is increasing and that lower <= upper.
 - Provide a canonical method that takes in a range and a domain. I don't think it's necessary to store the domain after this point, so it can be contained in the same type as non-canonical ranges.
 - Provide some type of `RangeSet` which represents multiple ranges (Guava's `ContiguousSet` is just a range that meets the `Set` interface, it doesn't support multiple ranges).

This would result in something like:
```racket
(define r (range #:excl 0 10))
(range/canonical r domain/integers) ; [1, 10)
```

**Comment by jackfirth** [comment] 2019-10-29 20:30
Oops, you're right about `ContiguousSet` v.s. `RangeSet`, sorry about the added confusion. I think `RangeSet` is a very useful thing to have and we ought to provide it.

Enforcing that `lower <= upper` sounds like a good idea to me. Any case where it isn't is almost certainly a bug caused by the programmer accidentally using some incorrect value for one of the range endpoints.

The cut system is mostly useful to me because it means that the shape of all ranges can be fully described by _one_ constructor. There can still be other constructors, and I think there should be because the cut-based constructor is pretty wordy in the common case. But the other constructors should only be convenience features that just provide a simpler interface to the cut-based constructor. We could even keep the cut-based constructor private, if we wanted to.

For range iteration order: I think we shouldn't iterate ranges. Ranges aren't sequences. There could be functions like `in-range` that consume a range and a step size and return a sequence, but that's more like an external extra feature that _uses_ ranges.

**Comment by jackfirth** [comment] 2019-10-31 03:04
Based on my experience with ranges in Java, I think the major use cases of ranges are:

1. Optional arguments to functions that query databases / other kinds of storage layers. For instance, a `list-customer-orders` function that optionally accepts a timestamp range, which it uses when generating some SQL query.

2. Range sets and maps. For instance, a range set is often a very useful and compact representation of a set of allowed characters or bytes. And range maps are great ways to represent timelines / version histories.

3. Filtering. It's useful to limit some collection to only the values that lie within some range.

But as for iteration, I have never once needed to do that. Array-like containers are often easier to just iterate like ordinary generic sequences. I don't think iteration is the main use case for ranges. I could see the potential if you're doing some slicing and dicing of strings and bytestrings or vectors, as a preprocessing step where you extract out the elements you need into their own compact data structure for later querying. If you have some specific use cases you're looking to apply ranges to in real world code, I'd love to hear about them.

**Comment by jackfirth** [comment] 2019-12-28 21:23
As of #373, Rebellion now has a basic range system. There's a couple of directions to go from here:

- Range collection types for sets and dicts of (disconnected) ranges. These collections are naturally sorted, so this might require interfaces for sorted sets and sorted dicts.
- Address discreteness, possibly with something similar to Guava's [`DiscreteDomain<C>`](https://github.com/google/guava/wiki/RangesExplained#discrete-domains) abstraction. Maybe a whole separate `discrete-range?` API?
- Add a contiguous set implementation (views a single discrete bounded range as a finite set).
- Quality-of-life features, like a reducer that determines the range of a sequence, or an `(in-range/c range)` contract combinator.

**Comment by jackfirth** [comment] 2021-01-22 08:44
Closing this since the range API has been merged for awhile now and any new changes and additions probably deserve their own issues.

**Closed by jackfirth** 2021-01-22 08:44 UTC
Labels: enhancement, needs api design
